In [22]:
# Importing necessary Libraries
import pandas as pd
import numpy as np

In [23]:
# Using IRIS Dataset
filename = "Iris.csv"
Data = pd.read_csv(filename)
Data

,Id,SepalLengthCm,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,3.5,1.4,0.2,Iris-setosa
1,2,4.9,3.0,1.4,0.2,Iris-setosa
2,3,4.7,3.2,1.3,0.2,Iris-setosa
3,4,4.6,3.1,1.5,0.2,Iris-setosa
4,5,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...
145,146,6.7,3.0,5.2,2.3,Iris-virginica
146,147,6.3,2.5,5.0,1.9,Iris-virginica
147,148,6.5,3.0,5.2,2.0,Iris-virginica
148,149,6.2,3.4,5.4,2.3,Iris-virginica
149,150,5.9,3.0,5.1,1.8,Iris-virginica

## Sepal_Length

In [24]:
Sepal_Length = Data.get('SepalLengthCm').to_numpy()
Sepal_Length

array([5.1, 4.9, 4.7, 4.6, 5. , 5.4, 4.6, 5. , 4.4, 4.9, 5.4, 4.8, 4.8,
       4.3, 5.8, 5.7, 5.4, 5.1, 5.7, 5.1, 5.4, 5.1, 4.6, 5.1, 4.8, 5. ,
       5. , 5.2, 5.2, 4.7, 4.8, 5.4, 5.2, 5.5, 4.9, 5. , 5.5, 4.9, 4.4,
       5.1, 5. , 4.5, 4.4, 5. , 5.1, 4.8, 5.1, 4.6, 5.3, 5. , 7. , 6.4,
       6.9, 5.5, 6.5, 5.7, 6.3, 4.9, 6.6, 5.2, 5. , 5.9, 6. , 6.1, 5.6,
       6.7, 5.6, 5.8, 6.2, 5.6, 5.9, 6.1, 6.3, 6.1, 6.4, 6.6, 6.8, 6.7,
       6. , 5.7, 5.5, 5.5, 5.8, 6. , 5.4, 6. , 6.7, 6.3, 5.6, 5.5, 5.5,
       6.1, 5.8, 5. , 5.6, 5.7, 5.7, 6.2, 5.1, 5.7, 6.3, 5.8, 7.1, 6.3,
       6.5, 7.6, 4.9, 7.3, 6.7, 7.2, 6.5, 6.4, 6.8, 5.7, 5.8, 6.4, 6.5,
       7.7, 7.7, 6. , 6.9, 5.6, 7.7, 6.3, 6.7, 7.2, 6.2, 6.1, 6.4, 7.2,
       7.4, 7.9, 6.4, 6.3, 6.1, 7.7, 6.3, 6.4, 6. , 6.9, 6.7, 6.9, 5.8,
       6.8, 6.7, 6.7, 6.3, 6.5, 6.2, 5.9])

In [25]:
Sorted = np.sort(Sepal_Length)
print(Sorted)
Mean = round(np.mean(Sepal_Length), 1)
Min = round(np.min(Sepal_Length), 1)
Max = round(np.max(Sepal_Length), 1)
print()
print(f"Minimum value: {Min}")
print(f"Maximum value: {Max}")
print(f"Mean of Data: {Mean}\n")

Range = (Max-Min)/3

SL_Small = []
S_Range = Min+Range
SL_Medium = []
M_Range = S_Range+Range
SL_Large = []
L_Range = M_Range+Range

print(f"Small Ranges: {Min}-{S_Range}.")
for i in range(150):
    if Sorted[i] < S_Range:
        SL_Small.append(Sorted[i])
print(SL_Small)
print(f"\nMedium Ranges: {S_Range}-{M_Range}.")
for i in range(150):
    if Sorted[i] < M_Range and Sorted[i] >= S_Range:
        SL_Medium.append(Sorted[i])
print(SL_Medium)
print(f"\nLarge Ranges: {L_Range}-{Max}.")
for i in range(150):
    if Sorted[i] <= Max and Sorted[i] >= M_Range:
        SL_Large.append(Sorted[i])
print(SL_Large)
SL = []

for i in range(150):
        if Sepal_Length[i] in SL_Small:
            SL.append("S")
        elif Sepal_Length[i] in SL_Medium:
            SL.append("M")
        elif Sepal_Length[i] in SL_Large:
            SL.append("L")
        
print(SL)

Data.insert(2, "SL", SL, True)
Data

[4.3 4.4 4.4 4.4 4.5 4.6 4.6 4.6 4.6 4.7 4.7 4.8 4.8 4.8 4.8 4.8 4.9 4.9
 4.9 4.9 4.9 4.9 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.  5.1 5.1 5.1 5.1
 5.1 5.1 5.1 5.1 5.1 5.2 5.2 5.2 5.2 5.3 5.4 5.4 5.4 5.4 5.4 5.4 5.5 5.5
 5.5 5.5 5.5 5.5 5.5 5.6 5.6 5.6 5.6 5.6 5.6 5.7 5.7 5.7 5.7 5.7 5.7 5.7
 5.7 5.8 5.8 5.8 5.8 5.8 5.8 5.8 5.9 5.9 5.9 6.  6.  6.  6.  6.  6.  6.1
 6.1 6.1 6.1 6.1 6.1 6.2 6.2 6.2 6.2 6.3 6.3 6.3 6.3 6.3 6.3 6.3 6.3 6.3
 6.4 6.4 6.4 6.4 6.4 6.4 6.4 6.5 6.5 6.5 6.5 6.5 6.6 6.6 6.7 6.7 6.7 6.7
 6.7 6.7 6.7 6.7 6.8 6.8 6.8 6.9 6.9 6.9 6.9 7.  7.1 7.2 7.2 7.2 7.3 7.4
 7.6 7.7 7.7 7.7 7.7 7.9]

Minimum value: 4.3
Maximum value: 7.9
Mean of Data: 5.8

Small Ranges: 4.3-5.5.
[4.3, 4.4, 4.4, 4.4, 4.5, 4.6, 4.6, 4.6, 4.6, 4.7, 4.7, 4.8, 4.8, 4.8, 4.8, 4.8, 4.9, 4.9, 4.9, 4.9, 4.9, 4.9, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.0, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.2, 5.2, 5.2, 5.2, 5.3, 5.4, 5.4, 5.4, 5.4, 5.4, 5.4]

Medium Ranges: 5.5-6.7.
[5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.5, 5.6, 5.6, 5.6, 5.6, 5.6, 5.6, 5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.7, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.8, 5.9, 5.9, 5.9, 6.0, 6.0, 6.0, 6.0, 6.0, 6.0, 6.1, 6.1, 6.1, 6.1, 6.1, 6.1, 6.2, 6.2, 6.2, 6.2, 6.3, 6.3, 6.3, 6.3, 6.3, 6.3, 6.3, 6.3, 6.3, 6.4, 6.4, 6.4, 6.4, 6.4, 6.4, 6.4, 6.5, 6.5, 6.5, 6.5, 6.5, 6.6, 6.6]

Large Ranges: 7.9-7.9.
[6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.7, 6.8, 6.8, 6.8, 6.9, 6.9, 6.9, 6.9, 7.0, 7.1, 7.2, 7.2, 7.2, 7.3, 7.4, 7.6, 7.7, 7.7, 7.7, 7.7, 7.9]
['S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'M', 'M', 'S', 'S', 'M', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'M', 'S', 'S', 'M', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'L', 'M', 'L', 'M', 'M', 'M', 'M', 'S', 'M', 'S', 'S', 'M', 'M', 'M', 'M', 'L', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'L', 'L', 'M', 'M', 'M', 'M', 'M', 'M', 'S', 'M', 'L', 'M', 'M', 'M', 'M', 'M', 'M', 'S', 'M', 'M', 'M', 'M', 'S', 'M', 'M', 'M', 'L', 'M', 'M', 'L', 'S', 'L', 'L', 'L', 'M', 'M', 'L', 'M', 'M', 'M', 'M', 'L', 'L', 'M', 'L', 'M', 'L', 'M', 'L', 'L', 'M', 'M', 'M', 'L', 'L', 'L', 'M', 'M', 'M', 'L', 'M', 'M', 'M', 'L', 'L', 'L', 'M', 'L', 'L', 'L', 'M', 'M', 'M', 'M']

,Id,SepalLengthCm,SL,SepalWidthCm,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,S,3.5,1.4,0.2,Iris-setosa
1,2,4.9,S,3.0,1.4,0.2,Iris-setosa
2,3,4.7,S,3.2,1.3,0.2,Iris-setosa
3,4,4.6,S,3.1,1.5,0.2,Iris-setosa
4,5,5.0,S,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...,...
145,146,6.7,L,3.0,5.2,2.3,Iris-virginica
146,147,6.3,M,2.5,5.0,1.9,Iris-virginica
147,148,6.5,M,3.0,5.2,2.0,Iris-virginica
148,149,6.2,M,3.4,5.4,2.3,Iris-virginica
149,150,5.9,M,3.0,5.1,1.8,Iris-virginica

## Sepal_Width

In [26]:
Sepal_Width = Data.get('SepalWidthCm').to_numpy()
Sepal_Width

array([3.5, 3. , 3.2, 3.1, 3.6, 3.9, 3.4, 3.4, 2.9, 3.1, 3.7, 3.4, 3. ,
       3. , 4. , 4.4, 3.9, 3.5, 3.8, 3.8, 3.4, 3.7, 3.6, 3.3, 3.4, 3. ,
       3.4, 3.5, 3.4, 3.2, 3.1, 3.4, 4.1, 4.2, 3.1, 3.2, 3.5, 3.1, 3. ,
       3.4, 3.5, 2.3, 3.2, 3.5, 3.8, 3. , 3.8, 3.2, 3.7, 3.3, 3.2, 3.2,
       3.1, 2.3, 2.8, 2.8, 3.3, 2.4, 2.9, 2.7, 2. , 3. , 2.2, 2.9, 2.9,
       3.1, 3. , 2.7, 2.2, 2.5, 3.2, 2.8, 2.5, 2.8, 2.9, 3. , 2.8, 3. ,
       2.9, 2.6, 2.4, 2.4, 2.7, 2.7, 3. , 3.4, 3.1, 2.3, 3. , 2.5, 2.6,
       3. , 2.6, 2.3, 2.7, 3. , 2.9, 2.9, 2.5, 2.8, 3.3, 2.7, 3. , 2.9,
       3. , 3. , 2.5, 2.9, 2.5, 3.6, 3.2, 2.7, 3. , 2.5, 2.8, 3.2, 3. ,
       3.8, 2.6, 2.2, 3.2, 2.8, 2.8, 2.7, 3.3, 3.2, 2.8, 3. , 2.8, 3. ,
       2.8, 3.8, 2.8, 2.8, 2.6, 3. , 3.4, 3.1, 3. , 3.1, 3.1, 3.1, 2.7,
       3.2, 3.3, 3. , 2.5, 3. , 3.4, 3. ])

In [27]:
Sorted = np.sort(Sepal_Width)
print(Sorted)
Mean = round(np.mean(Sepal_Width), 1)
Min = round(np.min(Sepal_Width), 1)
Max = round(np.max(Sepal_Width), 1)
print()
print(f"Minimum value: {Min}")
print(f"Maximum value: {Max}")
print(f"Mean of Data: {Mean}\n")

Range = (Max-Min)/3

SW_Small = []
S_Range = round(Min+Range, 1)
SW_Medium = []
M_Range = round(S_Range+Range, 1)
SW_Large = []
L_Range = round(M_Range+Range, 1)

print(f"Small Ranges: {Min}-{S_Range}.")
for i in range(150):
    if Sorted[i] < S_Range:
        SW_Small.append(Sorted[i])
print(SW_Small)
print(f"\nMedium Ranges: {S_Range}-{M_Range}.")
for i in range(150):
    if Sorted[i] < M_Range and Sorted[i] >= S_Range:
        SW_Medium.append(Sorted[i])
print(SW_Medium)
print(f"\nLarge Ranges: {L_Range}-{Max}.")
for i in range(150):
    if Sorted[i] <= Max and Sorted[i] >= M_Range:
        SW_Large.append(Sorted[i])
print(SW_Large)
SW = []

for i in range(150):
        if Sepal_Width[i] in SW_Small:
            SW.append("S")
        elif Sepal_Width[i] in SW_Medium:
            SW.append("M")
        elif Sepal_Width[i] in SW_Large:
            SW.append("L")
        
print(SW)

Data.insert(4, "SW", SW, True)
Data

[2.  2.2 2.2 2.2 2.3 2.3 2.3 2.3 2.4 2.4 2.4 2.5 2.5 2.5 2.5 2.5 2.5 2.5
 2.5 2.6 2.6 2.6 2.6 2.6 2.7 2.7 2.7 2.7 2.7 2.7 2.7 2.7 2.7 2.8 2.8 2.8
 2.8 2.8 2.8 2.8 2.8 2.8 2.8 2.8 2.8 2.8 2.8 2.9 2.9 2.9 2.9 2.9 2.9 2.9
 2.9 2.9 2.9 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.
 3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.  3.1 3.1 3.1 3.1 3.1 3.1 3.1
 3.1 3.1 3.1 3.1 3.1 3.2 3.2 3.2 3.2 3.2 3.2 3.2 3.2 3.2 3.2 3.2 3.2 3.2
 3.3 3.3 3.3 3.3 3.3 3.3 3.4 3.4 3.4 3.4 3.4 3.4 3.4 3.4 3.4 3.4 3.4 3.4
 3.5 3.5 3.5 3.5 3.5 3.5 3.6 3.6 3.6 3.7 3.7 3.7 3.8 3.8 3.8 3.8 3.8 3.8
 3.9 3.9 4.  4.1 4.2 4.4]

Minimum value: 2.0
Maximum value: 4.4
Mean of Data: 3.1

Small Ranges: 2.0-2.8.
[2.0, 2.2, 2.2, 2.2, 2.3, 2.3, 2.3, 2.3, 2.4, 2.4, 2.4, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.6, 2.6, 2.6, 2.6, 2.6, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7, 2.7]

Medium Ranges: 2.8-3.6.
[2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.8, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 2.9, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.1, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.2, 3.3, 3.3, 3.3, 3.3, 3.3, 3.3, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.4, 3.5, 3.5, 3.5, 3.5, 3.5, 3.5]

Large Ranges: 4.4-4.4.
[3.6, 3.6, 3.6, 3.7, 3.7, 3.7, 3.8, 3.8, 3.8, 3.8, 3.8, 3.8, 3.9, 3.9, 4.0, 4.1, 4.2, 4.4]
['M', 'M', 'M', 'M', 'L', 'L', 'M', 'M', 'M', 'M', 'L', 'M', 'M', 'M', 'L', 'L', 'L', 'M', 'L', 'L', 'M', 'L', 'L', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'L', 'L', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'S', 'M', 'M', 'L', 'M', 'L', 'M', 'L', 'M', 'M', 'M', 'M', 'S', 'M', 'M', 'M', 'S', 'M', 'S', 'S', 'M', 'S', 'M', 'M', 'M', 'M', 'S', 'S', 'S', 'M', 'M', 'S', 'M', 'M', 'M', 'M', 'M', 'M', 'S', 'S', 'S', 'S', 'S', 'M', 'M', 'M', 'S', 'M', 'S', 'S', 'M', 'S', 'S', 'S', 'M', 'M', 'M', 'S', 'M', 'M', 'S', 'M', 'M', 'M', 'M', 'S', 'M', 'S', 'L', 'M', 'S', 'M', 'S', 'M', 'M', 'M', 'L', 'S', 'S', 'M', 'M', 'M', 'S', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'L', 'M', 'M', 'S', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'S', 'M', 'M', 'M', 'S', 'M', 'M', 'M']

,Id,SepalLengthCm,SL,SepalWidthCm,SW,PetalLengthCm,PetalWidthCm,Species
0,1,5.1,S,3.5,M,1.4,0.2,Iris-setosa
1,2,4.9,S,3.0,M,1.4,0.2,Iris-setosa
2,3,4.7,S,3.2,M,1.3,0.2,Iris-setosa
3,4,4.6,S,3.1,M,1.5,0.2,Iris-setosa
4,5,5.0,S,3.6,L,1.4,0.2,Iris-setosa
...,...,...,...,...,...,...,...,...
145,146,6.7,L,3.0,M,5.2,2.3,Iris-virginica
146,147,6.3,M,2.5,S,5.0,1.9,Iris-virginica
147,148,6.5,M,3.0,M,5.2,2.0,Iris-virginica
148,149,6.2,M,3.4,M,5.4,2.3,Iris-virginica
149,150,5.9,M,3.0,M,5.1,1.8,Iris-virginica

## Petal_Length

In [28]:
Petal_Length = Data.get('PetalLengthCm').to_numpy()
Petal_Length

array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4,
       1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6,
       1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.5, 1.3,
       1.5, 1.3, 1.3, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5,
       4.9, 4. , 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4. , 4.7, 3.6,
       4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8, 5. ,
       4.5, 3.5, 3.8, 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4. , 4.4,
       4.6, 4. , 3.3, 4.2, 4.2, 4.2, 4.3, 3. , 4.1, 6. , 5.1, 5.9, 5.6,
       5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 5.5, 5. , 5.1, 5.3, 5.5,
       6.7, 6.9, 5. , 5.7, 4.9, 6.7, 4.9, 5.7, 6. , 4.8, 4.9, 5.6, 5.8,
       6.1, 6.4, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 5.6, 5.1, 5.1,
       5.9, 5.7, 5.2, 5. , 5.2, 5.4, 5.1])

In [29]:
Sorted = np.sort(Petal_Length)
print(Sorted)
Mean = round(np.mean(Petal_Length), 1)
Min = round(np.min(Petal_Length), 1)
Max = round(np.max(Petal_Length), 1)
print()
print(f"Minimum value: {Min}")
print(f"Maximum value: {Max}")
print(f"Mean of Data: {Mean}\n")

Range = (Max-Min)/3

PL_Small = []
S_Range = round(Min+Range, 1)
PL_Medium = []
M_Range = round(S_Range+Range, 1)
PL_Large = []
L_Range = round(M_Range+Range, 1)

print(f"Small Ranges: {Min}-{S_Range}.")
for i in range(150):
    if Sorted[i] < S_Range:
        PL_Small.append(Sorted[i])
print(PL_Small)
print(f"\nMedium Ranges: {S_Range}-{M_Range}.")
for i in range(150):
    if Sorted[i] < M_Range and Sorted[i] >= S_Range:
        PL_Medium.append(Sorted[i])
print(PL_Medium)
print(f"\nLarge Ranges: {L_Range}-{Max}.")
for i in range(150):
    if Sorted[i] <= Max and Sorted[i] >= M_Range:
        PL_Large.append(Sorted[i])
print(PL_Large)
PL = []

for i in range(150):
        if Petal_Length[i] in PL_Small:
            PL.append("S")
        elif Petal_Length[i] in PL_Medium:
            PL.append("M")
        elif Petal_Length[i] in PL_Large:
            PL.append("L")
        
print(PL)

Data.insert(6, "PL", PL, True)
Data

[1.  1.1 1.2 1.2 1.3 1.3 1.3 1.3 1.3 1.3 1.3 1.4 1.4 1.4 1.4 1.4 1.4 1.4
 1.4 1.4 1.4 1.4 1.4 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5
 1.5 1.6 1.6 1.6 1.6 1.6 1.6 1.6 1.7 1.7 1.7 1.7 1.9 1.9 3.  3.3 3.3 3.5
 3.5 3.6 3.7 3.8 3.9 3.9 3.9 4.  4.  4.  4.  4.  4.1 4.1 4.1 4.2 4.2 4.2
 4.2 4.3 4.3 4.4 4.4 4.4 4.4 4.5 4.5 4.5 4.5 4.5 4.5 4.5 4.5 4.6 4.6 4.6
 4.7 4.7 4.7 4.7 4.7 4.8 4.8 4.8 4.8 4.9 4.9 4.9 4.9 4.9 5.  5.  5.  5.
 5.1 5.1 5.1 5.1 5.1 5.1 5.1 5.1 5.2 5.2 5.3 5.3 5.4 5.4 5.5 5.5 5.5 5.6
 5.6 5.6 5.6 5.6 5.6 5.7 5.7 5.7 5.8 5.8 5.8 5.9 5.9 6.  6.  6.1 6.1 6.1
 6.3 6.4 6.6 6.7 6.7 6.9]

Minimum value: 1.0
Maximum value: 6.9
Mean of Data: 3.8

Small Ranges: 1.0-3.0.
[1.0, 1.1, 1.2, 1.2, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.6, 1.6, 1.6, 1.6, 1.6, 1.6, 1.6, 1.7, 1.7, 1.7, 1.7, 1.9, 1.9]

Medium Ranges: 3.0-5.0.
[3.0, 3.3, 3.3, 3.5, 3.5, 3.6, 3.7, 3.8, 3.9, 3.9, 3.9, 4.0, 4.0, 4.0, 4.0, 4.0, 4.1, 4.1, 4.1, 4.2, 4.2, 4.2, 4.2, 4.3, 4.3, 4.4, 4.4, 4.4, 4.4, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.5, 4.6, 4.6, 4.6, 4.7, 4.7, 4.7, 4.7, 4.7, 4.8, 4.8, 4.8, 4.8, 4.9, 4.9, 4.9, 4.9, 4.9]

Large Ranges: 7.0-6.9.
[5.0, 5.0, 5.0, 5.0, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.1, 5.2, 5.2, 5.3, 5.3, 5.4, 5.4, 5.5, 5.5, 5.5, 5.6, 5.6, 5.6, 5.6, 5.6, 5.6, 5.7, 5.7, 5.7, 5.8, 5.8, 5.8, 5.9, 5.9, 6.0, 6.0, 6.1, 6.1, 6.1, 6.3, 6.4, 6.6, 6.7, 6.7, 6.9]
['S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'L', 'M', 'M', 'M', 'M', 'M', 'L', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'L', 'L', 'L', 'L', 'L', 'L', 'M', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'M', 'L', 'M', 'L', 'L', 'M', 'M', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'M', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L']

,Id,SepalLengthCm,SL,SepalWidthCm,SW,PetalLengthCm,PL,PetalWidthCm,Species
0,1,5.1,S,3.5,M,1.4,S,0.2,Iris-setosa
1,2,4.9,S,3.0,M,1.4,S,0.2,Iris-setosa
2,3,4.7,S,3.2,M,1.3,S,0.2,Iris-setosa
3,4,4.6,S,3.1,M,1.5,S,0.2,Iris-setosa
4,5,5.0,S,3.6,L,1.4,S,0.2,Iris-setosa
...,...,...,...,...,...,...,...,...,...
145,146,6.7,L,3.0,M,5.2,L,2.3,Iris-virginica
146,147,6.3,M,2.5,S,5.0,L,1.9,Iris-virginica
147,148,6.5,M,3.0,M,5.2,L,2.0,Iris-virginica
148,149,6.2,M,3.4,M,5.4,L,2.3,Iris-virginica
149,150,5.9,M,3.0,M,5.1,L,1.8,Iris-virginica

## Petal_Width

In [30]:
Petal_Width = Data.get('PetalWidthCm').to_numpy()
Petal_Width

array([0.2, 0.2, 0.2, 0.2, 0.2, 0.4, 0.3, 0.2, 0.2, 0.1, 0.2, 0.2, 0.1,
       0.1, 0.2, 0.4, 0.4, 0.3, 0.3, 0.3, 0.2, 0.4, 0.2, 0.5, 0.2, 0.2,
       0.4, 0.2, 0.2, 0.2, 0.2, 0.4, 0.1, 0.2, 0.1, 0.2, 0.2, 0.1, 0.2,
       0.2, 0.3, 0.3, 0.2, 0.6, 0.4, 0.3, 0.2, 0.2, 0.2, 0.2, 1.4, 1.5,
       1.5, 1.3, 1.5, 1.3, 1.6, 1. , 1.3, 1.4, 1. , 1.5, 1. , 1.4, 1.3,
       1.4, 1.5, 1. , 1.5, 1.1, 1.8, 1.3, 1.5, 1.2, 1.3, 1.4, 1.4, 1.7,
       1.5, 1. , 1.1, 1. , 1.2, 1.6, 1.5, 1.6, 1.5, 1.3, 1.3, 1.3, 1.2,
       1.4, 1.2, 1. , 1.3, 1.2, 1.3, 1.3, 1.1, 1.3, 2.5, 1.9, 2.1, 1.8,
       2.2, 2.1, 1.7, 1.8, 1.8, 2.5, 2. , 1.9, 2.1, 2. , 2.4, 2.3, 1.8,
       2.2, 2.3, 1.5, 2.3, 2. , 2. , 1.8, 2.1, 1.8, 1.8, 1.8, 2.1, 1.6,
       1.9, 2. , 2.2, 1.5, 1.4, 2.3, 2.4, 1.8, 1.8, 2.1, 2.4, 2.3, 1.9,
       2.3, 2.5, 2.3, 1.9, 2. , 2.3, 1.8])

In [31]:
Sorted = np.sort(Petal_Width)
print(Sorted)
Mean = round(np.mean(Petal_Width), 1)
Min = round(np.min(Petal_Width), 1)
Max = round(np.max(Petal_Width), 1)
print()
print(f"Minimum value: {Min}")
print(f"Maximum value: {Max}")
print(f"Mean of Data: {Mean}\n")

Range = (Max-Min)/3

PW_Small = []
S_Range = round(Min+Range, 1)
PW_Medium = []
M_Range = round(S_Range+Range, 1)
PW_Large = []
L_Range = round(M_Range+Range, 1)

print(f"Small Ranges: {Min}-{S_Range}.")
for i in range(150):
    if Sorted[i] < S_Range:
        PW_Small.append(Sorted[i])
print(PW_Small)
print(f"\nMedium Ranges: {S_Range}-{M_Range}.")
for i in range(150):
    if Sorted[i] < M_Range and Sorted[i] >= S_Range:
        PW_Medium.append(Sorted[i])
print(PW_Medium)
print(f"\nLarge Ranges: {L_Range}-{Max}.")
for i in range(150):
    if Sorted[i] <= Max and Sorted[i] >= M_Range:
        PW_Large.append(Sorted[i])
print(PW_Large)
PW = []

for i in range(150):
        if Petal_Width[i] in PW_Small:
            PW.append("S")
        elif Petal_Width[i] in PW_Medium:
            PW.append("M")
        elif Petal_Width[i] in PW_Large:
            PW.append("L")
        
print(PW)

Data.insert(8, "PW", PW, True)
Data

[0.1 0.1 0.1 0.1 0.1 0.1 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2
 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.2 0.3 0.3
 0.3 0.3 0.3 0.3 0.3 0.4 0.4 0.4 0.4 0.4 0.4 0.4 0.5 0.6 1.  1.  1.  1.
 1.  1.  1.  1.1 1.1 1.1 1.2 1.2 1.2 1.2 1.2 1.3 1.3 1.3 1.3 1.3 1.3 1.3
 1.3 1.3 1.3 1.3 1.3 1.3 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.4 1.5 1.5 1.5 1.5
 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.5 1.6 1.6 1.6 1.6 1.7 1.7 1.8 1.8 1.8 1.8
 1.8 1.8 1.8 1.8 1.8 1.8 1.8 1.8 1.9 1.9 1.9 1.9 1.9 2.  2.  2.  2.  2.
 2.  2.1 2.1 2.1 2.1 2.1 2.1 2.2 2.2 2.2 2.3 2.3 2.3 2.3 2.3 2.3 2.3 2.3
 2.4 2.4 2.4 2.5 2.5 2.5]

Minimum value: 0.1
Maximum value: 2.5
Mean of Data: 1.2

Small Ranges: 0.1-0.9.
[0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.2, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.3, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.4, 0.5, 0.6]

Medium Ranges: 0.9-1.7.
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.1, 1.1, 1.1, 1.2, 1.2, 1.2, 1.2, 1.2, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.4, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.5, 1.6, 1.6, 1.6, 1.6]

Large Ranges: 2.5-2.5.
[1.7, 1.7, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.8, 1.9, 1.9, 1.9, 1.9, 1.9, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.1, 2.1, 2.1, 2.1, 2.1, 2.1, 2.2, 2.2, 2.2, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.3, 2.4, 2.4, 2.4, 2.5, 2.5, 2.5]
['S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'L', 'M', 'M', 'M', 'M', 'M', 'M', 'L', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'M', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'M', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'M', 'L', 'L', 'L', 'M', 'M', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L', 'L']

,Id,SepalLengthCm,SL,SepalWidthCm,SW,PetalLengthCm,PL,PetalWidthCm,PW,Species
0,1,5.1,S,3.5,M,1.4,S,0.2,S,Iris-setosa
1,2,4.9,S,3.0,M,1.4,S,0.2,S,Iris-setosa
2,3,4.7,S,3.2,M,1.3,S,0.2,S,Iris-setosa
3,4,4.6,S,3.1,M,1.5,S,0.2,S,Iris-setosa
4,5,5.0,S,3.6,L,1.4,S,0.2,S,Iris-setosa
...,...,...,...,...,...,...,...,...,...,...
145,146,6.7,L,3.0,M,5.2,L,2.3,L,Iris-virginica
146,147,6.3,M,2.5,S,5.0,L,1.9,L,Iris-virginica
147,148,6.5,M,3.0,M,5.2,L,2.0,L,Iris-virginica
148,149,6.2,M,3.4,M,5.4,L,2.3,L,Iris-virginica
149,150,5.9,M,3.0,M,5.1,L,1.8,L,Iris-virginica

In [32]:
Data['SL'].unique()

array(['S', 'M', 'L'], dtype=object)

## Calculating Probability

In [52]:
category = input("Enter Feature Category: ")
value = float(input(f"Enter {category}: "))
flower = input("Enter the Flower: ")

if category == 'SL':
    if value in SL_Small:
        value = 'S'
    elif value in SL_Medium:
        value = 'M'
    elif value in SL_Large:
        value = 'L'
elif category == 'SW':
    if value in SW_Small:
        value = 'S'
    elif value in SW_Medium:
        value = 'M'
    elif value in SW_Large:
        value = 'L'
elif category == 'PL':
    if value in PL_Small:
        value = 'S'
    elif value in PL_Medium:
        value = 'M'
    elif value in PL_Large:
        value = 'L'
elif category == 'PW':
    if value in PW_Small:
        value = 'S'
    elif value in PW_Medium:
        value = 'M'
    elif value in PW_Large:
        value = 'L'

count = Data[(Data[category] == value) & (Data['Species'] == flower)].shape[0]
prob = count/150

print(f"Probability of {flower} with {category} {value} is: {round(prob, 2)}.")

Enter Feature Category: SL
Enter SL: 5.5
Enter the Flower: Iris-setosa
Probability of Iris-setosa with SL M is: 0.03.